### ISSUE TITLE
Rake mongoid_search:index not able to run

### ISSUE THREAD

**Issue by davidwparker** [mauriciozaffari/mongoid_search#67]
I am unable to run the rake task "mongoid_search:index".

As a work-around, I just copied the source and created it locally within my project.

Stack trace:

```terminal
rake mongoid_search:index --trace
rake aborted!
Don't know how to build task 'mongoid_search:index'
/Users/dparker/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task_manager.rb:49:in `[]'
/Users/dparker/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:148:in `invoke_task'
/Users/dparker/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/dparker/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:106:in `each'
/Users/dparker/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:106:in `block in top_level'
/Users/dparker/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:115:in `run_with_threads'
/Users/dparker/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:100:in `top_level'
/Users/dparker/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:78:in `block in run'
/Users/dparker/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/dparker/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/Users/dparker/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/bin/rake:33:in `<top (required)>'
/Users/dparker/.rvm/gems/ruby-2.0.0-p247/bin/rake:23:in `load'
/Users/dparker/.rvm/gems/ruby-2.0.0-p247/bin/rake:23:in `<main>'
/Users/dparker/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
/Users/dparker/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'
```

Gems:
  * mongoid (4.0.0 d0fc225)
  * mongoid-paperclip (0.0.8)
  * mongoid_search (0.3.2)
  * rake (10.1.0)

**Comment by i8ramin** [comment]
+1 .. `gem 'mongoid_search', github: 'mauriciozaffari/mongoid_search', branch: 'master'` works, but just doing `gem 'mongoid_search'` does not.

**Comment by Loschcode** [comment]
I can't believe years after they didn't even check to fix this. +1 for the fork or something

**Comment by dblock** [comment]
I can help adding maintainers here but i hope @mauriciozaffari should step in to do that so that this gem can be maintained.

**Comment by mauriciozaffari** [comment]
Sorry, I haven't being using this gem nor maintaining it for a long time now. My understanding is that a new release should fix the issue, is this correct? If that's the case, I can just do it.

**Comment by dblock** [comment]
Lets try to get a new group of people to help out who actually use it? Anyone here wants to volunteer to clean things up, make a release and such?

Also check out https://github.com/mongoid/mongoid_fulltext that might be more evolved.

**Comment by AnishKhatri** [comment]
@dblock https://github.com/mongoid/mongoid_fulltext is evolved but it does not support to index two fields. You can index only one field and if you want to index two fields, you need to create two different index. 

mongoid_fulltext does not support auto complete as it does not have :all options to ngram.

If anyone has these issues resolved, I would like to know how it can be resolved.

**Comment by dblock** [comment]
@AnishKhatri open feature requests at least (or better contribute) to that gem
