### ISSUE TITLE
All documents are returned when we use special characters

### ISSUE THREAD

**Issue by rjurado01** [mauriciozaffari/mongoid_search#79]
If I use special characters for search it returns all documents:

```ruby
class User
  include Mongoid::Document
  include Mongoid::Search

  field :name
  search_in :name
end

User.create( name: 'lala' )
User.create( name: 'lele' )
User.create( name: 'lolo' )

User.count
 => 3

# it should return 0 documents but returns all document 
User.full_text_search('.').count
 => 3
User.full_text_search('+').count
 => 3

# it works ok
User.full_text_search('a').count
 => 1
```

This is a bug ?

**Comment by tkowalczyk** [comment]
exactly any news about it?

**Comment by Shwetakale** [comment]
I think this is not bug. [Here](https://github.com/mauriciozaffari/mongoid_search/issues/79) all punctuation symbols are replaced by space('  ') , So you are seeing this behavior. I am not getting use case where user need to search by punctuation marks. If this use case is valid then I think picking up punctuation marks from configuration will do needful like  ```Mongoid::Search.ignore_list``` is picked up from configuration. 

Picking up punctuation list from configuration functionality is currently unavailable in this gem. If anyone needs it I can send PR.

**Comment by mauriciozaffari** [comment]
@Shwetakale @tkowalczyk @rjurado01 There's an open PR #63 about this, but it does not includes any tests.

**Comment by Shwetakale** [comment]
@mauriciozaffari Missed this pull request. Let me know if any help needed on that PR.
