### ISSUE TITLE
Cannot paginate or sort on search results

### ISSUE THREAD

**Issue by aashish** [mauriciozaffari/mongoid_search#81]
Hi, 
I cannot use desc, asc or paginate while full_text_search.
Model.full_text_search(query).desc("updated_at")  is not working. 
And also cannot sort on relavence. 
Thanks, 
Aashish

**Comment by Shwetakale** [comment]
@aashish I tried this out and it seems to be working fine. 

    Model.full_text_search(query).desc("updated_at")

returns mongoid criteria which is expected. I am curious to know in which condition it is not working. Can you give steps to reproduce this?
