### ISSUE TITLE
Getting this to search for a field named 'Tags' instead of '_keyword'

### ISSUE THREAD

**Issue by geneviethebeezy** [mauriciozaffari/mongoid_search#86]
Is there any way I can get this to search for 'Tags'? I already have a database created and I do not have a '_keywords' field.

**Comment by Ashviniv** [comment]
You can add following lines in your model:
```
    include Mongoid::Search
    search_in :tags
```
and run the following command in the console to get all the tags in _keywords field
`Model.all.each(&:save)`
In this way you can search for tags.
