### ISSUE TITLE
Start_with

### ISSUE THREAD

**Issue by benjaminharel** [mauriciozaffari/mongoid_search#91]
Is there an option to search only when _keywords has an entry that "starts_with" query string?

**Comment by Ashviniv** [comment]
If you want to search for entries that starts with query string, you can just enter start letters as query string. As, mongoid search accepts partial searching too, you will get expected result.Just make sure default match option is enabled. i.e ``` match: any ``` Added test case to prove this.
```
context " _keywords has an entry that starts_with query" do
  before(:each) do
    class Product
      include Mongoid::Document 
      include Mongoid::Search   
      field :brand
      field :name
      search_in :brand, :name
    end
    @product = Product.create(name: "apple", brand: "mybrand")
  end

  it "should return results in search with a partial word by default" do
    expect(@product._keywords).to match_array(["apple", "mybrand"])
    expect(Product.full_text_search("m").size).to eq(1)
    expect(Product.full_text_search("apples").size).to eq(0)
  end
end
```
But, if you enter "apples" as query string and expecting all the results that starts with "a" or "apple".You wont get any results.You will get results that matches with "apples" only.

**Comment by Shwetakale** [comment]
@benjaminharel Yes ```mongoid_search``` provides such option.

@Ashviniv You are right @benjaminharel needs to enable ```partial search``` option but @benjaminharel  wants to search words that starts_with query string. With your example if  ```_keywords``` has entry 'pineapple' and if query sting is 'apple' then it will be matched.

I think solution would be to enable ```regex_search``` by adding following following configuration 

```ruby
      config.regex_search = true
```
and for always Matching partial words on the beginning add following configuration
```ruby    
      config.regex = Proc.new { |query| /^#{query}/ }
```
Hope this helps.

**Comment by Ashviniv** [comment]
@Shwetakale Thanx..:+1:
